name = "memory-note"
kv_namespaces = [
    { binding = "MEMORY_NOTE", id = "2191dab41f4b4f738d98493d4754b411", preview_id = "" }
]
compatibility_date = "2023-01-01"
compatibility_flags = [ "nodejs_compat" ]
